In [1]:
import numpy as np
import pandas as pd 
import torch
import torch.nn as nn
from sklearn.model_selection import train_test_split 
from sklearn.preprocessing import StandardScaler 
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv("breast-cancer.csv")
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [3]:
df.drop(columns = ['id'], inplace = True)
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

In [4]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size = 0.2)

In [5]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test  = scaler.transform(X_test)

In [6]:
encoder = LabelEncoder()
y_train_encoder = encoder.fit_transform(y_train)
y_test_encoder = encoder.transform(y_test)

In [7]:
X_train_tensor = torch.from_numpy(X_train).float()
X_test_tensor = torch.from_numpy(X_test).float()
y_train_tensor = torch.from_numpy(y_train_encoder).float()
y_test_tensor = torch.from_numpy(y_test_encoder).float()

CustomDataset Class
=

In [8]:
from torch.utils.data import Dataset, DataLoader 

class CustomDataset(Dataset):
    def __init__(self, features, labels):
        self.features = features
        self.labels = labels

    def __len__(self):
        return len(self.features)

    def __getitem__(self, idx):
        return self.features[idx], self.labels[idx]

Dataset Object
=

In [9]:
train_dataset = CustomDataset(X_train_tensor, y_train_tensor)
test_dataset = CustomDataset(X_test_tensor, y_test_tensor)

DataLoader Object
=

In [10]:
train_loader = DataLoader(train_dataset, batch_size= 32, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size= 32, shuffle=True)

Define Model
=

In [11]:
class MySimpleNN(nn.Module):
    def __init__(self, num_features):
        super(). __init__()
        self.network = nn.Sequential(
            nn.Linear(num_features, 1),
            nn.Sigmoid()
        )

    def forward(self, features):
        out = self.network(features)
        return out

Important Parameters
=

In [12]:
learning_rate = 0.1
epochs = 25

Model Creation
=

In [13]:
# Create model 
model = MySimpleNN(X_train_tensor.shape[1])

# Define optimizer
optimizer = torch.optim.SGD(model.parameters(), lr = learning_rate)

# Loss function
loss_function = nn.BCELoss()

Training Pipeline
=

In [14]:
for epochs in range(epochs):
    for batch_features, batch_labels, in train_loader:
            
          # Forward pass
            y_pred = model(X_train_tensor)
        
            # Loss calculation
            loss = loss_function(y_pred, y_train_tensor.view(-1, 1))
        
            # Clear Gradient
            optimizer.zero_grad()
        
            # Backward pass
            loss.backward()
        
            # Update parameters
            optimizer.step()
        
            print(f"Epochs : {epochs + 1}, Loss : {loss.item()}")

Epochs : 1, Loss : 0.672440230846405
Epochs : 1, Loss : 0.5194019079208374
Epochs : 1, Loss : 0.4361268877983093
Epochs : 1, Loss : 0.3836078345775604
Epochs : 1, Loss : 0.3467758595943451
Epochs : 1, Loss : 0.31917524337768555
Epochs : 1, Loss : 0.2975385785102844
Epochs : 1, Loss : 0.2800111174583435
Epochs : 1, Loss : 0.265453040599823
Epochs : 1, Loss : 0.25312089920043945
Epochs : 1, Loss : 0.24250730872154236
Epochs : 1, Loss : 0.23325280845165253
Epochs : 1, Loss : 0.2250949740409851
Epochs : 1, Loss : 0.2178371101617813
Epochs : 1, Loss : 0.21132856607437134
Epochs : 2, Loss : 0.2054518163204193
Epochs : 2, Loss : 0.20011353492736816
Epochs : 2, Loss : 0.1952386349439621
Epochs : 2, Loss : 0.19076581299304962
Epochs : 2, Loss : 0.1866445243358612
Epochs : 2, Loss : 0.18283258378505707
Epochs : 2, Loss : 0.17929457128047943
Epochs : 2, Loss : 0.17600038647651672
Epochs : 2, Loss : 0.17292429506778717
Epochs : 2, Loss : 0.17004422843456268
Epochs : 2, Loss : 0.16734099388122559
Epochs : 2, Loss : 0.16479791700839996
Epochs : 2, Loss : 0.16240037977695465
Epochs : 2, Loss : 0.16013558208942413
Epochs : 2, Loss : 0.1579921543598175
Epochs : 3, Loss : 0.1559600532054901
Epochs : 3, Loss : 0.15403029322624207
Epochs : 3, Loss : 0.15219493210315704
Epochs : 3, Loss : 0.15044672787189484
Epochs : 3, Loss : 0.14877930283546448
Epochs : 3, Loss : 0.14718680083751678
Epochs : 3, Loss : 0.14566397666931152
Epochs : 3, Loss : 0.14420601725578308
Epochs : 3, Loss : 0.14280864596366882
Epochs : 3, Loss : 0.14146792888641357
Epochs : 3, Loss : 0.14018018543720245
Epochs : 3, Loss : 0.1389421820640564
Epochs : 3, Loss : 0.13775083422660828
Epochs : 3, Loss : 0.1366034299135208
Epochs : 3, Loss : 0.13549736142158508
Epochs : 4, Loss : 0.13443031907081604
Epochs : 4, Loss : 0.1334000825881958
Epochs : 4, Loss : 0.1324046403169632
Epochs : 4, Loss : 0.131442129611969
Epochs : 4, Loss : 0.1305108368396759
Epochs : 4, Loss : 0.1296091228723526
Epochs : 4, Loss : 0.1287355273962021
Epochs : 4, Loss : 0.12788860499858856
Epochs : 4, Loss : 0.12706708908081055
Epochs : 4, Loss : 0.12626974284648895
Epochs : 4, Loss : 0.12549543380737305
Epochs : 4, Loss : 0.12474311888217926
Epochs : 4, Loss : 0.12401176989078522
Epochs : 4, Loss : 0.1233004480600357
Epochs : 4, Loss : 0.12260826677083969
Epochs : 5, Loss : 0.1219344288110733
Epochs : 5, Loss : 0.12127812206745148
Epochs : 5, Loss : 0.1206386461853981
Epochs : 5, Loss : 0.12001525610685349
Epochs : 5, Loss : 0.11940733343362808
Epochs : 5, Loss : 0.11881423741579056
Epochs : 5, Loss : 0.11823541671037674
Epochs : 5, Loss : 0.11767029017210007
Epochs : 5, Loss : 0.11711832880973816
Epochs : 5, Loss : 0.11657906323671341
Epochs : 5, Loss : 0.11605197936296463
Epochs : 5, Loss : 0.11553667485713959
Epochs : 5, Loss : 0.11503268778324127
Epochs : 5, Loss : 0.11453964561223984
Epochs : 5, Loss : 0.11405711621046066
Epochs : 6, Loss : 0.11358477920293808
Epochs : 6, Loss : 0.11312227696180344
Epochs : 6, Loss : 0.11266923695802689
Epochs : 6, Loss : 0.11222539842128754
Epochs : 6, Loss : 0.11179041862487793
Epochs : 6, Loss : 0.11136403679847717
Epochs : 6, Loss : 0.1109459325671196
Epochs : 6, Loss : 0.1105358749628067
Epochs : 6, Loss : 0.11013361811637878
Epochs : 6, Loss : 0.10973890870809555
Epochs : 6, Loss : 0.1093514934182167
Epochs : 6, Loss : 0.10897119343280792
Epochs : 6, Loss : 0.1085977628827095
Epochs : 6, Loss : 0.10823099315166473
Epochs : 6, Loss : 0.10787072032690048
Epochs : 7, Loss : 0.10751672834157944
Epochs : 7, Loss : 0.10716884583234787
Epochs : 7, Loss : 0.10682690143585205
Epochs : 7, Loss : 0.10649074614048004
Epochs : 7, Loss : 0.10616017132997513
Epochs : 7, Loss : 0.10583506524562836
Epochs : 7, Loss : 0.1055152639746666
Epochs : 7, Loss : 0.10520060360431671
Epochs : 7, Loss : 0.10489100217819214
Epochs : 7, Loss : 0.10458628088235855
Epochs : 7, Loss : 0.10428633540868759
Epochs : 7, Loss : 0.10399100929498672
Epochs : 7, Loss : 0.10370022803544998
Epochs : 7, Loss : 0.10341385006904602
Epochs : 7, Loss : 0.10313177108764648
Epochs : 8, Loss : 0.10285387933254242
Epochs : 8, Loss : 0.10258007049560547
Epochs : 8, Loss : 0.10231027007102966
Epochs : 8, Loss : 0.10204433649778366
Epochs : 8, Loss : 0.10178221017122269
Epochs : 8, Loss : 0.10152380913496017
Epochs : 8, Loss : 0.10126901417970657
Epochs : 8, Loss : 0.10101775079965591
Epochs : 8, Loss : 0.10076995939016342
Epochs : 8, Loss : 0.10052552074193954
Epochs : 8, Loss : 0.1002843976020813
Epochs : 8, Loss : 0.10004650056362152
Epochs : 8, Loss : 0.09981175512075424
Epochs : 8, Loss : 0.09958010166883469
Epochs : 8, Loss : 0.0993514433503151
Epochs : 9, Loss : 0.09912575036287308
Epochs : 9, Loss : 0.09890294075012207
Epochs : 9, Loss : 0.0986829549074173
Epochs : 9, Loss : 0.09846574813127518
Epochs : 9, Loss : 0.09825123101472855
Epochs : 9, Loss : 0.09803937375545502
Epochs : 9, Loss : 0.09783010929822922
Epochs : 9, Loss : 0.09762338548898697
Epochs : 9, Loss : 0.09741915017366409
Epochs : 9, Loss : 0.09721735119819641
Epochs : 9, Loss : 0.09701797366142273
Epochs : 9, Loss : 0.09682091325521469
Epochs : 9, Loss : 0.0966261476278305
Epochs : 9, Loss : 0.09643365442752838
Epochs : 9, Loss : 0.09624335169792175
Epochs : 10, Loss : 0.09605523198843002
Epochs : 10, Loss : 0.09586922824382782
Epochs : 10, Loss : 0.09568531066179276
Epochs : 10, Loss : 0.09550343453884125
Epochs : 10, Loss : 0.0953235849738121
Epochs : 10, Loss : 0.09514567255973816
Epochs : 10, Loss : 0.09496971219778061
Epochs : 10, Loss : 0.09479566663503647
Epochs : 10, Loss : 0.09462345391511917
Epochs : 10, Loss : 0.09445308148860931
Epochs : 10, Loss : 0.09428451955318451
Epochs : 10, Loss : 0.09411770850419998
Epochs : 10, Loss : 0.09395263344049454
Epochs : 10, Loss : 0.09378926455974579
Epochs : 10, Loss : 0.09362757205963135
Epochs : 11, Loss : 0.09346751868724823
Epochs : 11, Loss : 0.09330908209085464
Epochs : 11, Loss : 0.0931522324681282
Epochs : 11, Loss : 0.09299695491790771
Epochs : 11, Loss : 0.092843197286129
Epochs : 11, Loss : 0.09269096702337265
Epochs : 11, Loss : 0.0925402119755745
Epochs : 11, Loss : 0.09239090979099274
Epochs : 11, Loss : 0.09224305301904678
Epochs : 11, Loss : 0.09209661930799484
Epochs : 11, Loss : 0.09195155650377274
Epochs : 11, Loss : 0.09180786460638046
Epochs : 11, Loss : 0.09166552126407623
Epochs : 11, Loss : 0.09152451157569885
Epochs : 11, Loss : 0.09138478338718414
Epochs : 12, Loss : 0.0912463515996933
Epochs : 12, Loss : 0.09110917896032333
Epochs : 12, Loss : 0.09097325801849365
Epochs : 12, Loss : 0.09083855897188187
Epochs : 12, Loss : 0.09070505201816559
Epochs : 12, Loss : 0.09057275205850601
Epochs : 12, Loss : 0.09044160693883896
Epochs : 12, Loss : 0.09031162410974503
Epochs : 12, Loss : 0.09018275141716003
Epochs : 12, Loss : 0.09005501866340637
Epochs : 12, Loss : 0.08992838859558105
Epochs : 12, Loss : 0.0898028165102005
Epochs : 12, Loss : 0.0896783322095871
Epochs : 12, Loss : 0.08955490589141846
Epochs : 12, Loss : 0.08943250775337219
Epochs : 13, Loss : 0.0893111377954483
Epochs : 13, Loss : 0.089190773665905
Epochs : 13, Loss : 0.08907140046358109
Epochs : 13, Loss : 0.08895301073789597
Epochs : 13, Loss : 0.08883559703826904
Epochs : 13, Loss : 0.08871912211179733
Epochs : 13, Loss : 0.08860359340906143
Epochs : 13, Loss : 0.08848898857831955
Epochs : 13, Loss : 0.08837529271841049
Epochs : 13, Loss : 0.08826250582933426
Epochs : 13, Loss : 0.08815059810876846
Epochs : 13, Loss : 0.0880395770072937
Epochs : 13, Loss : 0.08792942017316818
Epochs : 13, Loss : 0.08782010525465012
Epochs : 13, Loss : 0.0877116471529007
Epochs : 14, Loss : 0.08760403096675873
Epochs : 14, Loss : 0.08749720454216003
Epochs : 14, Loss : 0.0873912051320076
Epochs : 14, Loss : 0.08728601038455963
Epochs : 14, Loss : 0.08718158304691315
Epochs : 14, Loss : 0.08707795292139053
Epochs : 14, Loss : 0.0869750902056694
Epochs : 14, Loss : 0.08687297999858856
Epochs : 14, Loss : 0.08677160739898682
Epochs : 14, Loss : 0.08667100220918655
Epochs : 14, Loss : 0.0865711122751236
Epochs : 14, Loss : 0.08647193759679794
Epochs : 14, Loss : 0.08637348562479019
Epochs : 14, Loss : 0.08627573400735855
Epochs : 14, Loss : 0.08617867529392242
Epochs : 15, Loss : 0.08608230203390121
Epochs : 15, Loss : 0.08598659932613373
Epochs : 15, Loss : 0.08589158952236176
Epochs : 15, Loss : 0.08579722046852112
Epochs : 15, Loss : 0.08570350706577301
Epochs : 15, Loss : 0.08561044186353683
Epochs : 15, Loss : 0.08551802486181259
Epochs : 15, Loss : 0.0854262262582779
Epochs : 15, Loss : 0.08533505350351334
Epochs : 15, Loss : 0.08524449914693832
Epochs : 15, Loss : 0.08515454828739166
Epochs : 15, Loss : 0.08506520092487335
Epochs : 15, Loss : 0.0849764496088028
Epochs : 15, Loss : 0.08488830178976059
Epochs : 15, Loss : 0.08480070531368256
Epochs : 16, Loss : 0.08471370488405228
Epochs : 16, Loss : 0.08462726324796677
Epochs : 16, Loss : 0.08454138785600662
Epochs : 16, Loss : 0.08445606380701065
Epochs : 16, Loss : 0.08437128365039825
Epochs : 16, Loss : 0.08428706228733063
Epochs : 16, Loss : 0.08420336246490479
Epochs : 16, Loss : 0.08412020653486252
Epochs : 16, Loss : 0.08403756469488144
Epochs : 16, Loss : 0.08395545184612274
Epochs : 16, Loss : 0.08387383818626404
Epochs : 16, Loss : 0.08379274606704712
Epochs : 16, Loss : 0.0837121531367302
Epochs : 16, Loss : 0.08363205939531326
Epochs : 16, Loss : 0.08355244994163513
Epochs : 17, Loss : 0.0834733322262764
Epochs : 17, Loss : 0.08339469134807587
Epochs : 17, Loss : 0.08331652730703354
Epochs : 17, Loss : 0.08323884010314941
Epochs : 17, Loss : 0.0831616148352623
Epochs : 17, Loss : 0.08308485150337219
Epochs : 17, Loss : 0.08300855755805969
Epochs : 17, Loss : 0.08293270319700241
Epochs : 17, Loss : 0.08285730332136154
Epochs : 17, Loss : 0.08278234302997589
Epochs : 17, Loss : 0.08270780742168427
Epochs : 17, Loss : 0.08263371884822845
Epochs : 17, Loss : 0.08256006240844727
Epochs : 17, Loss : 0.0824868306517601
Epochs : 17, Loss : 0.08241400867700577
Epochs : 18, Loss : 0.08234162628650665
Epochs : 18, Loss : 0.08226963132619858
Epochs : 18, Loss : 0.08219806849956512
Epochs : 18, Loss : 0.08212689310312271
Epochs : 18, Loss : 0.08205612003803253
Epochs : 18, Loss : 0.08198574930429459
Epochs : 18, Loss : 0.08191575855016708
Epochs : 18, Loss : 0.08184616267681122
Epochs : 18, Loss : 0.08177695423364639
Epochs : 18, Loss : 0.0817081406712532
Epochs : 18, Loss : 0.08163968473672867
Epochs : 18, Loss : 0.08157160878181458
Epochs : 18, Loss : 0.08150390535593033
Epochs : 18, Loss : 0.08143657445907593
Epochs : 18, Loss : 0.08136960864067078
Epochs : 19, Loss : 0.08130298554897308
Epochs : 19, Loss : 0.08123672753572464
Epochs : 19, Loss : 0.08117082715034485
Epochs : 19, Loss : 0.08110527694225311
Epochs : 19, Loss : 0.08104006946086884
Epochs : 19, Loss : 0.08097520470619202
Epochs : 19, Loss : 0.08091069012880325
Epochs : 19, Loss : 0.08084651082754135
Epochs : 19, Loss : 0.08078265935182571
Epochs : 19, Loss : 0.08071914315223694
Epochs : 19, Loss : 0.08065594732761383
Epochs : 19, Loss : 0.08059309422969818
Epochs : 19, Loss : 0.080530546605587
Epochs : 19, Loss : 0.0804683193564415
Epochs : 19, Loss : 0.08040641248226166
Epochs : 20, Loss : 0.08034483343362808
Epochs : 20, Loss : 0.08028354495763779
Epochs : 20, Loss : 0.08022256940603256
Epochs : 20, Loss : 0.080161914229393
Epochs : 20, Loss : 0.08010154962539673
Epochs : 20, Loss : 0.08004149049520493
Epochs : 20, Loss : 0.079981729388237
Epochs : 20, Loss : 0.07992225885391235
Epochs : 20, Loss : 0.07986307889223099
Epochs : 20, Loss : 0.0798041969537735
Epochs : 20, Loss : 0.07974559813737869
Epochs : 20, Loss : 0.07968728244304657
Epochs : 20, Loss : 0.07962924987077713
Epochs : 20, Loss : 0.07957150787115097
Epochs : 20, Loss : 0.0795140340924263
Epochs : 21, Loss : 0.07945684343576431
Epochs : 21, Loss : 0.07939991354942322
Epochs : 21, Loss : 0.0793432667851448
Epochs : 21, Loss : 0.07928688079118729
Epochs : 21, Loss : 0.07923075556755066
Epochs : 21, Loss : 0.07917491346597672
Epochs : 21, Loss : 0.07911931723356247
Epochs : 21, Loss : 0.07906399667263031
Epochs : 21, Loss : 0.07900892943143845
Epochs : 21, Loss : 0.07895410805940628
Epochs : 21, Loss : 0.0788995549082756
Epochs : 21, Loss : 0.07884524017572403
Epochs : 21, Loss : 0.07879117876291275
Epochs : 21, Loss : 0.07873736321926117
Epochs : 21, Loss : 0.07868380099534988
Epochs : 22, Loss : 0.0786304846405983
Epochs : 22, Loss : 0.07857739925384521
Epochs : 22, Loss : 0.07852455973625183
Epochs : 22, Loss : 0.07847195118665695
Epochs : 22, Loss : 0.07841958850622177
Epochs : 22, Loss : 0.07836746424436569
Epochs : 22, Loss : 0.07831554859876633
Epochs : 22, Loss : 0.07826388627290726
Epochs : 22, Loss : 0.07821245491504669
Epochs : 22, Loss : 0.07816124707460403
Epochs : 22, Loss : 0.07811025530099869
Epochs : 22, Loss : 0.07805948704481125
Epochs : 22, Loss : 0.07800894975662231
Epochs : 22, Loss : 0.07795862853527069
Epochs : 22, Loss : 0.07790851593017578
Epochs : 23, Loss : 0.07785864174365997
Epochs : 23, Loss : 0.07780896872282028
Epochs : 23, Loss : 0.0777595117688179
Epochs : 23, Loss : 0.07771026343107224
Epochs : 23, Loss : 0.07766123861074448
Epochs : 23, Loss : 0.07761240750551224
Epochs : 23, Loss : 0.07756379246711731
Epochs : 23, Loss : 0.0775153785943985
Epochs : 23, Loss : 0.0774671733379364
Epochs : 23, Loss : 0.07741916179656982
Epochs : 23, Loss : 0.07737136632204056
Epochs : 23, Loss : 0.07732376456260681
Epochs : 23, Loss : 0.07727634906768799
Epochs : 23, Loss : 0.07722914218902588
Epochs : 23, Loss : 0.07718212902545929
Epochs : 24, Loss : 0.07713532447814941
Epochs : 24, Loss : 0.07708868384361267
Epochs : 24, Loss : 0.07704225182533264
Epochs : 24, Loss : 0.07699602097272873
Epochs : 24, Loss : 0.07694995403289795
Epochs : 24, Loss : 0.07690408825874329
Epochs : 24, Loss : 0.07685840129852295
Epochs : 24, Loss : 0.07681290060281754
Epochs : 24, Loss : 0.07676759362220764
Epochs : 24, Loss : 0.07672246545553207
Epochs : 24, Loss : 0.07667750865221024
Epochs : 24, Loss : 0.07663273811340332
Epochs : 24, Loss : 0.07658814638853073
Epochs : 24, Loss : 0.07654372602701187
Epochs : 24, Loss : 0.07649948447942734
Epochs : 25, Loss : 0.07645541429519653
Epochs : 25, Loss : 0.07641153037548065
Epochs : 25, Loss : 0.0763678103685379
Epochs : 25, Loss : 0.07632425427436829
Epochs : 25, Loss : 0.076280876994133
Epochs : 25, Loss : 0.07623767107725143
Epochs : 25, Loss : 0.07619462162256241
Epochs : 25, Loss : 0.07615174353122711
Epochs : 25, Loss : 0.07610902935266495
Epochs : 25, Loss : 0.07606648653745651
Epochs : 25, Loss : 0.07602410763502121
Epochs : 25, Loss : 0.07598187774419785
Epochs : 25, Loss : 0.07593982666730881
Epochs : 25, Loss : 0.07589790970087051
Epochs : 25, Loss : 0.07585617899894714

Evaluation
=

In [15]:
# Model evaluation using test_loader
model.eval() # set the model to evaluation mode
accuracy_list = []

with torch.no_grad():
    for batch_features, batch_labels in test_loader:

        # Forwad pass 
        y_pred = model(batch_features)
        y_pred = (y_pred > 0.5).float()


        # calculate accuracy for the current batch
        batch_accuracy = (y_pred.view(-1) == batch_labels).float().mean().item()
        accuracy_list.append(batch_accuracy)


# Calculate overall accuracy 
overall_accuracy = sum(accuracy_list) / len(accuracy_list)
print(f"Accuracy : {overall_accuracy : .4f}")

Accuracy :  0.9922